const albums = [
    {
      Title: 'Hybrid Theory',
      Year: 2000,
      Author: 'Linkin Park',
      Duration: '49 minuti',
      Poster: 'https://m.media-amazon.com/images/I/613BBVSBnEL._UX358_FMwebp_QL85_.jpg',
      Genre: 'Hard rock',
      Vote: 5,
      tracks: ['Papercut', 'One Step Closer', 'With You', 'Points of Authority', 'Crawling', 'Runaway', 'By MYself', 'In the End', 'A Place for My Head', 'Forgotten', 'Cure for the Itch', 'Pushing Me Away',],
    },
    {
      Title: 'Meteora',
      Year: 2003,
      Author: 'Linkin Park',
      Duration: '36 minuti',
      Poster: 'https://m.media-amazon.com/images/I/41Gr1rXBNXL._UX358_FMwebp_QL85_.jpg',
      Genre: 'Hard rock',
      Vote: 4.5,
      tracks: ['Foreword', 'Don\'t Stay', 'Somewhere I Belong', 'Lying from You', 'Hit the Floor', 'Easier to Run', 'Faint', 'Figure.09', 'Breaking the Habit', 'From the Inside', 'Nobody\'s Listening', 'Session', 'Numb'],
    },
    {
      Title: 'Ecliptica',
      Year: 1999,
      Author: 'Sonata Arctica',
      Duration: '56 minuti',
      Poster: 'https://m.media-amazon.com/images/I/61ofPhH-I+L._UX358_FMwebp_QL85_.jpg',
      Genre: 'Power metal',
      Vote: 5,
      tracks: ['Blank File', 'My Land', '8th Commandment', 'Replica', 'Kingdom for a Heart', 'FullMoon', 'Letter to Dana', 'UnOpened', 'Picturing the Past', 'Destruction Preventer', 'Mary-Lou', 'Letter to Dana (Returned to Sender)'],
    },
    {
      Title: 'Silence',
      Year: 2001,
      Author: 'Sonata Arctica',
      Duration: '1 ora e 13 minuti',
      Poster: 'https://m.media-amazon.com/images/I/61nMj3M4NgL._UX358_FMwebp_QL85_.jpg',
      Genre: 'Power metal',
      Vote: 4,
      tracks: ['...Of Silence', 'Weballergy', 'False News Travel Fast', 'The End of This Chapter', 'Black Sheep', 'Land of The Free', 'Last Drop Falls', 'San Sebastian', 'Sing In Silence', 'Revontulet', 'Tallulah', 'Wolf & Raven', 'Respect The Wilderness', 'The power Of One', 'Peacemaker'],
    },
    {
      Title: '÷ (Divide)',
      Year: 2017,
      Author: 'Ed Sheeran',
      Duration: '46 minuti',
      Poster: 'https://m.media-amazon.com/images/I/61fPYcsUGRL._UX358_FMwebp_QL85_.jpg',
      Genre: 'Pop',
      Vote: 5,
      tracks: ['Eraser', 'Castle on the Hill', 'Dive', 'Shape of You', 'Perfect', 'Galway Girl', 'Happier', 'New Man', 'Hearts Don\'t Break Around Here', 'What Do I Know?', 'How Would You Feel (Paean)', 'Supermarket Flowers'],
    },
    {
      Title: 'Disincanto',
      Year: 2002,
      Author: 'Mango',
      Duration: '50 minuti',
      Poster: 'https://m.media-amazon.com/images/I/519YHr1egML._UX358_FMwebp_QL85_.jpg',
      Genre: 'Pop',
      Vote: 3.5,
      tracks: ['Disincanto', 'Io sono sentimentale', 'La rondine', 'Un amore non torna', 'Non è amore da ridere', 'Fiore del mondo', 'Michelle', 'E mi basta il mare', 'Mi piaci accanto', 'Non moriremo mai', 'Ho consumato la notte', 'E mi consumo', 'Gli angeli non volano'],
    },
    {
      Title: 'A Night At The Opera',
      Year: 1975,
      Author: 'Queen',
      Duration: '43 minuti',
      Poster: 'https://m.media-amazon.com/images/I/51PUorlJEOL._UX358_FMwebp_QL85_.jpg',
      Genre: 'Hard rock',
      Vote: 3.5,
      tracks: ['Death on Two Legs', 'Lazing on a Sunday Afternoon', 'I\'m in Love with My Car', 'You\'re My Best Friend', '\'39', 'Sweet Lady', 'Seaside Rendezvous', 'The Prophet\'s Song', 'Love of My Life', 'Good Company', 'Bohemian Rhapsody', 'God Save the Queen'],
    },
    {
      Title: 'Californication',
      Year: 1999,
      Author: 'Red Hot Chili Peppers',
      Duration: '56 minuti',
      Poster: 'https://m.media-amazon.com/images/I/61QO9SogAUL._UX358_FMwebp_QL85_.jpg',
      Genre: 'Funk rock',
      Vote: 3,
      tracks: ['Around the World', 'Parallel Universe', 'Scar Tissue', 'Otherside', 'Get on Top', 'Californication', 'Easily', 'Porcelain', 'Emit Remmus', 'I Like Dirt', 'This Velvet Glove', 'Savior', 'Purple Stain', 'Right on Time', 'Road Trippin\''],
    },
    {
      Title: 'By the Way',
      Year: 2002,
      Author: 'Red Hot Chili Peppers',
      Duration: '1 ora e 8 minuti',
      Poster: 'https://m.media-amazon.com/images/I/61-unsHRmVL._UX358_FMwebp_QL85_.jpg',
      Genre: 'Pop rock',
      Vote: 3,
      tracks: ['By the Way', 'Universally Speaking', 'This Is the Place', 'Dosed', 'Don\'t Forget Me', 'The Zephyr Song', 'Can\'t Stop', 'I Could Die for You', 'Midnight', 'Throw Away Your Television', 'Cabron', 'Tear', 'On Mercury', 'Minor Thing', 'Warm Tape', 'Venice Queen'],
    },
    {
      Title: 'Mr. Simpatia',
      Year: 2004,
      Author: 'Fabri Fibra',
      Duration: '1 ora e 12 minuti',
      Poster: 'https://m.media-amazon.com/images/I/51q3Mi6QO-L._UX358_FMwebp_QL85_.jpg',
      Genre: 'Rap',
      Vote: 1,
      tracks: ['L\'uomo nel mirino', 'Gonfio così', 'Io non ti invidio', 'Venerdì diciassette', 'Solo una botta', 'Momenti no', 'Da questo locale', 'Rap in vena', 'Niente male', 'Faccio sul serio', 'Non crollo', 'Non fare la puttana', 'Voglio farti un regalo', 'Palle piene', 'Mr. Simpatia', 'Andiamo', 'Tienila su'],
    },
  ];